framework:
    secret: '%env(APP_SECRET)%'
    php_errors:
        log: true

    cache:
        # Redis
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: redis://localhost